apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-ctf
  labels:
    app: medusa-ctf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medusa-ctf
  template:
    metadata:
      labels:
        app: medusa-ctf
    spec:
      containers:
        - name: medusa-ctf
          image: registry.digitalocean.com/medusa-ctf/vulnerable-ctf-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: CTF_FLAG
              value: "Medusa{CTF_CHALLENGE_PHASE1_PASSED}"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: medusa-ctf-service
spec:
  selector:
    app: medusa-ctf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
